import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/navbar";
import { ModeToggle } from "@/components/theme/mode-toggle";
// import { ThemeProvider } from "@/components/theme/theme-provider";
// import UiOrientationContextProvider from "../contexts/uiOrientationContext";
import Providers from "./providers";
import UiOrientationContextProvider from "@/contexts/uiOrientationContext";
// import Home from "@/app/page";
// import Experience from "@/app/experience/page";
// import About from "@/app/about/page";
// import Projects from "@/app/projects/page";
// import Connect from "@/app/connect/page";
// import SlideProvider from "@/contexts/slideContext";
// const pages = [
//   { component: Home, name: "Home" },
//   { component: Experience, name: "Experience" },
//   { component: About, name: "About" },
//   { component: Projects, name: "Projects" },
//   { component: Connect, name: "Connect" },
// ];
// const pages = [
//   { component: <Home />, name: "Home" },
//   { component: <Experience />, name: "Experience" },
//   { component: <About />, name: "About" },
//   { component: <Projects />, name: "Projects" },
//   { component: <Connect />, name: "Connect" },
// ];

// import {
//   faB,
//   faCheckSquare,
//   faCoffee,
//   faDatabase,
//   faHouseLaptop,
//   faS,
//   faWindowMaximize,
// } from "@fortawesome/free-solid-svg-icons";
// import { library } from "@fortawesome/fontawesome-svg-core";
// import { ModeToggle } from "@/components/theme/mode-toggle";
// library.add(
//   faB,
//   faS,
//   faHouseLaptop,
//   faCheckSquare,
//   faCoffee,
//   faDatabase,
//   faWindowMaximize
// );

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="text-red-700 h-content">
      <body className={inter.className}>
        <UiOrientationContextProvider>
          <Navbar />
          <ModeToggle />
          <Providers>
            {/* <SlideProvider pages={pages}>
            {pages.map(({ component: Component }, index) => (
              <Component key={index} />
            ))}
          </SlideProvider> */}
            {children}
          </Providers>
        </UiOrientationContextProvider>
      </body>
    </html>
  );
}
