import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/navbar";
import { ModeToggle } from "@/components/theme/mode-toggle";
// import { ThemeProvider } from "@/components/theme/theme-provider";
// import UiOrientationContextProvider from "../contexts/uiOrientationContext";
import Providers from "./providers";

// import {
//   faB,
//   faCheckSquare,
//   faCoffee,
//   faDatabase,
//   faHouseLaptop,
//   faS,
//   faWindowMaximize,
// } from "@fortawesome/free-solid-svg-icons";
// import { library } from "@fortawesome/fontawesome-svg-core";
// import { ModeToggle } from "@/components/theme/mode-toggle";
// library.add(
//   faB,
//   faS,
//   faHouseLaptop,
//   faCheckSquare,
//   faCoffee,
//   faDatabase,
//   faWindowMaximize
// );

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <ModeToggle />
          {children}
        </Providers>
      </body>
    </html>
  );
}
